import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tailwindStyles from '../styles/tailwind.module.css'

export default function Home() {

  // get a4 div width and set the height to 1.414 times the width

  let Name = "text-gris text-xl text-center"

  let Title = "text-gris text-title text-left font-bold pt-1"

  let Intitule = "text-black text-nomComp text-left font-bold opacity-100"

  let Locdate = "text-gris text-[11px] text-right font-bold opacity-60"

  let Moi = "text-gris text-[11px] text-center font-bold opacity-60"

  let Desc = "text-black text-[11px] text-left py-[2px]"

  let line = "my-1 mx-auto w-92 h-[2px] bg-gray-300 rounded border-0 dark:bg-gray-700"

  let facteur = 1.2

  let a4Width = Math.ceil(595 * facteur)

  let a4Height = Math.ceil(842 * facteur)


  return (
    <div className={styles.container}>
      <Head>
        <title>CV Clément DELBARRE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>



        <div id="a4" className={`bg-white w-[${a4Width}px] h-[${a4Height}px] p-5`}>

          <p className={`${Name}`}>
            CLEMENT <span className='font-bold opacity-100 text-black'> DELBARRE </span>
          </p>


          <p className={`${Moi} py-1`}>
          <a href="https://www.linkedin.com/in/cl%C3%A9ment-delbarre-491159254/" > My Linkedin | </a> 
            <span>
            <a href="mailto:clement.delbarre@edu.ece.fr" > clement.delbarre@edu.ece.fr | </a>
            </span>
             07.84.32.25.54 | 
            <a href="https://github.com/RXT-Eago" > github.com/RXT-Eago </a>
             | TOEIC 820
          </p>

          <p className={`${Desc} pt-1 text-center`}>
            Développeur Full-Stack curieux et passionné, j'aime explorer et approfondir des domaines techniques inconnus pour développer des solutions innovantes.
          </p>

          <p className={`${Title}`}>
            Formation
          </p>
          <hr className={`${line}`}></hr>

          <div className="flex">

            <div className='w-2/3'>
              <p className={`${Desc} font-semibold`}>
                ECE Paris - Majeur Systèmes Information, Spécialisation Cybersécurité
              </p>
            </div>
            <div className='w-1/3'>
              <p className={`${Locdate}`}>
                2019 - 2024
              </p>
            </div>

          </div>
          <p className={`${Desc}`}>
            <span className='font-bold px-2'>• Cours:</span>   Sécurité des systèmes d'information, Reverse Engineering, Forensics, DevOps, Réseaux, Développement Web, Cryptographie
          </p>

          <div className="flex pt-2">

            <div className='w-4/5'>
              <p className={`${Desc} font-semibold`}>
                Bangor University - Semestre d'échange international
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Septembre - Décembre 2021
              </p>
            </div>

          </div>
          <p className={`${Desc}`}>
            <span className='font-bold px-2'>• Cours:</span>   UI-UX, Linux, Electronics
          </p>

          <p className={`${Title}`}>
            Skills
          </p>
          <hr className={`${line}`}></hr>

          <div className="flex">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>Languages:</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                TS, Python, Bash, Tailwaind, SQL, Java
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>Technologies:</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                ReactJS, NextJS, MongoDB, MySQL, Git, Docker, GitLab, CI/CD, Helm, K8s, Grafana, Prometheus
              </p>
            </div>


          </div>


          <p className={`${Title}`}>
            Expériences
          </p>

          <hr className={`${line}`}></hr>


          <div className="flex pt-2">
            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                LTMG | Skilink
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                {/* Date à ajouter */}
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-full'>
              <p className={`${Desc} font-semibold`}>
                CTO / Lead Developer
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Janvier 2025 - Aujourd'hui
              </p>
            </div>
          </div>
          <p className={`${Desc} pl-3`}>
            • Développement Full-Stack d'une plateforme SaaS d'édition de dossiers de compétences pour ESN et cabinets de conseil.
          </p>
          <p className={`${Desc} pl-3`}>
            • Conception et développement d'un pipeline d'extraction automatique de données depuis les CV via IA (OCR et LLM).
          </p>
          <p className={`${Desc} pl-3`}>
            • Développement d'un système de matching intelligent via RAG et LLM utilisant Vertex AI (Google Cloud) pour faire correspondre les profils aux appels d'offres.
          </p>
          <p className={`${Desc} pl-3`}>
            • Développement d'une interface de gestion centralisée permettant l'import de CV selon des templates personnalisables et l'export en PDF/Word.
          </p>
          <p className={`${Desc} pl-3`}>
            • Architecture et développement de l'API backend et du frontend avec des frameworks modernes (FastAPI, NextJS).
          </p>
          <p className={`${Desc} pl-3`}>
            • Mise en place de l'infrastructure DevOps avec Docker, Railway et Github Actions pour le déploiement.
          </p>
          <p className={`${Desc} font-medium`}>
            Outils: React, NextJS, FastAPI, Docker, Railway, GitLab CI, SQL, Redis, Grafana, Metabase, Sentry, Vertex AI, LLM, RAG.
          </p>



          <div className="flex pt-2">
            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                AXA & Conduent | Stratumn
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                {/* Date à ajouter */}
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-full'>
              <p className={`${Desc} font-semibold`}>
                Dev Full Stack
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                février 2025 - Aujourd'hui
              </p>
            </div>
          </div>
          <p className={`${Desc} pl-3`}>
            • Développement Full-Stack d'une plateforme logicielle basée sur la blockchain pour automatiser des workflows métier complexes dans le secteur de la réassurance.
          </p>
          <p className={`${Desc} pl-3`}>
            • Conception et implémentation de workflows pour les processus de ChargeBack en utilisant un DSL personnalisé.
          </p>
          <p className={`${Desc} pl-3`}>
            • Création d'un pipeline de génération de PDF scalable pour générer des documents PDF complexes avec pdf-lib.
          </p>
          <p className={`${Desc} pl-3`}>
            • Développement et déploiement de nouvelles fonctionnalités du backend au frontend en utilisant des frameworks modernes.
          </p>
          <p className={`${Desc} pl-3`}>
            • Travail au sein d'une équipe Agile Scrum, avec participation à la planification des sprints, aux revues et à la livraison des fonctionnalités.
          </p>
          <p className={`${Desc} font-medium`}>
            Outils: React, Vite, Nest JS, Docker, Kubernetes, GitLab CI, SQL, Redis, Grafana, Sentry.
          </p>


          <div className="flex pt-2">
            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                RATP | WasteTracker
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                {/* Date à ajouter */}
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-full'>
              <p className={`${Desc} font-semibold`}>
                Dev Full Stack
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Septembre 2024 - Février 2025
              </p>
            </div>
          </div>
          <p className={`${Desc} pl-3`}>
            • Développement d'une plateforme à grande échelle pour la gestion des déchets pour la RATP.
          </p>
          <p className={`${Desc} pl-3`}>
            • Construction de l'API Backend (Python, Flask) et conception de l'extraction des données des manifestes de déchets avec OCR et LLM.
          </p>
          <p className={`${Desc} pl-3`}>
            • Intégration de la communication en temps réel avec les API gouvernementales via des webhooks.
          </p>
          <p className={`${Desc} pl-3`}>
            • Implémentation de la couche d'analyse avec Metabase, déployée avec Helm et CI/CD personnalisée.
          </p>
          <p className={`${Desc} pl-3`}>
            • Amélioration du frontend de l'application à partir de maquettes Figma, amélioration globale de l'UX/UI.
          </p>
          <p className={`${Desc} font-medium`}>
            Outils: Python (Flask), React (Redux, Antd), Helm, Kubernetes, GitLab CI, Metabase.
          </p>


          {/* <div className="flex pt-2">
            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                MBDA
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Février - Août 2024
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-full'>
              <p className={`${Desc} font-semibold`}>
                Ingénieur Logiciel - Évolution et amélioration d'une application logicielle
              </p>
            </div>
          </div>
          <p className={`${Desc} pl-3`}>
            • Migration d'une application C++ existante vers une architecture avec un backend en Java et un frontend en React.
          </p>
          <p className={`${Desc} pl-3`}>
            • Gestion du cycle de développement.
          </p>
          <p className={`${Desc} pl-3`}>
            • Mise en place de scripts de déploiement et conteneurisation avec Docker.
          </p>
          <p className={`${Desc} pl-3`}>
            • Fourniture d'une documentation complète.
          </p>
          <p className={`${Desc} font-medium`}>
            Outils: Java, React, C++, Docker.
          </p> */}

         {/*  <div className="flex pt-2">
            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                Renault
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Avril - Août 2023
              </p>
            </div>
          </div>
          <div className="flex">
            <div className='w-full'>
              <p className={`${Desc} font-semibold`}>
                Ingénieur Logiciel - Android Automotive
              </p>
            </div>
          </div>
          <p className={`${Desc} pl-3`}>
            • Développement d'une application affichant la puissance de charge du véhicule.
          </p>
          <p className={`${Desc} pl-3`}>
            • Déploiement en version bêta sur 100 véhicules.
          </p>
          <p className={`${Desc} pl-3`}>
            • Création d'une application de notation pour les bornes de recharge après une session de charge.
          </p>
          <p className={`${Desc} pl-3`}>
            • Analyse de la congestion sur 1500 bornes de recharge.
          </p>
          <p className={`${Desc} font-medium`}>
            Outils: Android Automotive, Java, Kotlin.
          </p> */}




        
          {/* <div className="flex">

            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                AIRBUS Defense and Space
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Janvier - Février 2022
              </p>
            </div>

          </div>

          <p className={`${Desc}`}>
            • Coréalisation d'un didacticiel de services de messagerie confidentielle à destination de la Direction Générale de l'Armement.
          </p>
          <p className={`${Desc} pl-3`}>
            • Utilisation de la suite Adobe pour la réalisation de vidéos et de présentation.
          </p>
          <p className={`${Desc} pl-3`}>
            • Développement Web pour publication de la documentation.
          </p> */}


          {/*
          <div className="flex pt-2">

            <div className='w-3/4'>
              <p className={`${Desc}`}>
                Stage Ingénieur 2ème année
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Elancourt, 78990
              </p>
            </div>

          </div>
          
          <div className="flex">

            <div className='w-3/4'>
              <p className={`${Intitule}`}>
                Thales LAS France
              </p>
            </div>
            <div className='w-1/4'>
              <p className={`${Locdate}`}>
                Janvier - Fevrier 2021
              </p>
            </div>

          </div>

          <p className={`${Desc}`}>
            • Annotation d'images aériennes afin de détecter des véhicules. Ces images annotés sont ensuite utilisés pour l'entrainement d'un réseau de neurones.
          </p>
          */}





          <p className={`${Title}`}>
            Projets
          </p>
          <hr className={`${line}`}></hr>

          <div className="flex">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>TanHyper</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                Développement d'un indicateur technique boursier basé sur la tangente hyperbolique.
              </p>
            </div>
          </div>

          <div className="flex pt-1">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>DailyPeakCrypto</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                Création d'un bot de trading publiant des signaux d'achat/vente via Twitter (RSI + TD Sequential)
              </p>
            </div>
          </div>

          <div className="flex  pt-1">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>Fiat500e widget</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                Développement d'un widget pour la Fiat 500E permettant d'accéder à des informations sur son véhicule électrique
              </p>
            </div>
          </div>

          <div className="flex  pt-1">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>BackTestSoft</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                Développement d'un logiciel de backtest C++ pour tester des stratégies de trading.
              </p>
            </div>
          </div>

         
          <div className="flex  pt-1">
            <div className='w-24'>
              <p className={`${Desc}`}>
                <span className='font-bold'>Portfolio</span>

              </p>
            </div>
            <div className='w-auto'>
              <p className={`${Desc}`}>
                Réalisation d'un portfolio en ReactJS et Tailwind pour présenter mes projets et compétences.
              </p>
            </div>
          </div>



          <p className={`${Title} flex w-full`}>
            <div className='w-1/2 flex justify-start items-center'>
              Centre d'intérêt
            </div>
            <div className='w-1/2 flex justify-end justify-items-end items-center'>
              Portfolio
            </div>
          </p>
          <hr className={`${line}`}></hr>

          <p className={`${Desc} w-full px-1 flex`}>
            <div className='w-1/2 flex justify-start justify-items-end items-center font-medium'>
              Golf • Dev 
            </div>
            <div className={`${Locdate} w-1/2 flex justify-end justify-items-end items-center`}>
              <a href="https://clement-delbarre-web-site.vercel.app/" >
                https://clement-delbarre-web-site.vercel.app/
              </a>
            </div>
          </p>

          
          {/*<hr className={`${line}`}></hr>
          

          <div className="flex pt-1">

            <div className='w-3/5'>
              <div className=' rounded-xl w-16 h-16'>
                <img src="/assets/images/QRCode.png" alt="" />
              </div>
            </div>
            <div className='w-2/5'>
              <p className={`${Locdate}`}>
                <a href="https://clement-delbarre-web-site.vercel.app/" >
                https://clement-delbarre-web-site.vercel.app/
                </a>
              </p>
            </div>

          </div>
          */}






        </div>




      </main>

    </div>
  )
}